Repository Kernel360/f1-JDON-Frontend, pull requests merged in 2024-02, with the labels that each got.

#159 ✨ Feat : scrolToTop버튼 생성
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/pull_request_template.md
  src/App.jsx
  src/assets/icons/aroww-top.svg
  src/index.js
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/ScrollToTop.jsx
  src/pages/mainpage/SubmitBug.jsx
  src/styles/animations.scss
Labels: ✨ Feat

#168 🐛 Fix : DayPicker value값 코드 수정 #167
  package.json
  src/api/api.js
  src/components/common/new-daypicker/NewDayPicker.jsx
  src/pages/info/Done.jsx
  src/pages/info/SignupFail.jsx
  src/pages/mainpage/Main.jsx
  src/pages/sign-in/RedirectPage.jsx
  src/recoil/atoms.jsx
Labels: 🐛 Fix

#170 ✨Feat : 로그인 상태에 따른 main페이지 `내 맞춤 키워드`버튼 노출 처리
  src/pages/mainpage/StickyTabSection.jsx
Labels: ✨ Feat

#177 ✨ Feat : 로그인 상태에 따른 마이페이지 접근 처리 #176
  src/App.jsx
  src/components/common/card/VideoCard.jsx
  src/index.js
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/sign-in/TitleLogo.jsx
  src/pages/sign-in/index.scss
  src/recoil/atoms.jsx
Labels: ✨ Feat, 🐛 Fix

#179 💄 Design : jd 상세 퍼블리싱
  package.json
  src/App.jsx
  src/assets/icons/review_add.svg
  src/components/common/BackDrop.jsx
  src/components/common/card/CompanyCard.jsx
  src/pages/FavoritesVideo.jsx
  src/pages/coffeechat/CoffeeOpen.jsx
  src/pages/info/SignupFail.jsx
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/jd-detail/JdDetail.jsx
  src/pages/jd-detail/PopupFrame.jsx
  src/pages/jd-detail/ReviewItem.jsx
  src/pages/jd-detail/ReviewPopup.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/mock.js
  src/pages/jd-detail/usePopup.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/sign-in/FailPage.jsx
  src/pages/sign-in/RedirectPage copy.jsx
  src/pages/sign-in/RedirectPage.jsx
Labels: 🐛 Fix, ♻️ Refactor, 💄 Style

#182 ✨ Feat: CoffeeChatCard 의 조회
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/card/CardStyle.js
  src/components/common/card/CoffeeChatCard.jsx
  src/components/common/card/CoffeeChatCard/BadgeForJob.jsx
  src/components/common/card/CoffeeChatCard/BadgeForStatus.jsx
  src/components/common/card/CoffeeChatCard/CardBody.jsx
  src/components/common/card/CoffeeChatCard/CardHeader.jsx
  src/components/common/card/CoffeeChatCard/CoffeeChatCardStyle.js
  src/components/common/card/CoffeeChatCard/CoffeeInfoItem.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/pages/coffee-detail/CoffeeDetail.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/sign-in/RedirectPage.jsx
  src/utils/formatDate.js
Labels: ✨ Feat, ♻️ Refactor

#184 🚨 Hotfix : 검색어 입력 시 api 무한호출되는 문제 수정
  src/pages/coffee-detail/CoffeeDetailButtons.jsx
  src/pages/mainpage/HeaderWithSearchBar.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/useLoadData.jsx
Labels: 🐛 Fix, 🚨 Hotfix

#185 ✨ Feat : 공고 리스트 페이지 퍼블리싱 완료
  package.json
  src/App.jsx
  src/components/common/Header.jsx
  src/pages/PageStyles.js
  src/pages/jd-all/JDComponent.jsx
  src/pages/jd-all/JDPgNation.jsx
  src/pages/jd-all/JDSearchBar.jsx
  src/pages/jd-all/index.jsx
  src/pages/jd-all/mock.js
  src/pages/mainpage/CompanySection.jsx
Labels: ✨ Feat, 📦 Chore, 💄 Style

#186 🐛 Fix : 메인페이지 빈 검색어 오류 수정
  src/pages/mainpage/useLoadData.jsx
Labels: 🐛 Fix

#196 🚑️ Hotfix: 로그인 판별 api 인덱싱 수정
  src/App.jsx
  src/api/api.js
Labels: 🚨 Hotfix

#195 🐛 Fix : JD 목록페이지 페이지네이션 및 검색관련 오류 수정
  src/pages/jd-all/JDComponent.jsx
Labels: 🐛 Fix

#218 🐛 Fix: 02/29 수정 요청 사항
  src/pages/PageStyles.js
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/sign-in/SignIn.jsx
Labels: 🐛 Fix

#217 🐛 Fix : UI 수정 및 로그인 버튼 문구 변경 QA 반영
  src/App.jsx
  src/components/common/BottomNav.jsx
  src/components/common/new-input/NewInput.jsx
  src/pages/jd-all/JDBanner.jsx
  src/pages/jd-all/JDComponent.jsx
  src/pages/jd-all/index.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/sign-in/LoginBtn.jsx
  src/pages/sign-in/SignIn.jsx
Labels: 🐛 Fix
