Repository Kernel360/f1-JDON-Frontend, pull requests merged in 2024-03, with the labels that each got.

#219 🐛 Fix: jd 리뷰, 커피챗 상세 페이지 수정
  package-lock.json
  package.json
  src/components/common/card/CoffeeChatCard/BadgeForJob.jsx
  src/components/common/card/CoffeeChatCard/CardHeader.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/pages/coffee-detail/CoffeeChatInfo.jsx
  src/pages/coffee-detail/CoffeeDetail.jsx
  src/pages/coffee-detail/CoffeeDetailButtons.jsx
  src/pages/coffee-detail/HostInfoWithViewcount.jsx
  src/pages/jd-detail/ReviewItem.jsx
  src/pages/jd-detail/ReviewList.jsx
  src/pages/jd-detail/ReviewPopup.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/addReviewButton.jsx
  src/pages/jd-detail/useAddReview.jsx
  src/pages/jd-detail/useDeleteReview.jsx
  src/pages/jd-detail/useInfiniteScroll.jsx
  src/pages/jd-detail/useReviewPagination.jsx
Labels: ✨ Feat, 🐛 Fix, 💄 Style

#221 🐛 Fix : 커피챗 오픈, 데이피커 수정
  src/App.jsx
  src/components/common/card/CoffeeChatCard/CardHeader.jsx
  src/components/common/filters/Filters copy.jsx
  src/components/common/new-daypicker/NewDayPicker.jsx
  src/components/common/new-input/NewInput.jsx
  src/pages/coffee-detail/CoffeeChatInfo.jsx
  src/pages/coffeechat/CoffeeOpen.jsx
  src/pages/info/InFo.jsx
  src/pages/info/InFoBasic.jsx
  src/pages/info/InfoStyles.js
  src/pages/jd-detail/addReviewButton.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/recoil/atoms.jsx
Labels: ✨ Feat, 🐛 Fix

#222 🚨👨‍⚕️ HotQA: 급히 수정되어야 하는 이슈들 반영
  jsconfig.json
  package.json
  src/App.jsx
  src/components/common/navigation-btn/NavigationBtnStyles.js
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/constants/nickname.js
  src/pages/404/index.jsx
  src/pages/PageStyles.js
  src/pages/coffeechat/Coffee.jsx
  src/pages/info/InFoBasic.jsx
  src/pages/info/InfoStyles.js
  src/pages/jd-all/JDBanner.jsx
  src/pages/jd-all/index.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/mainpage/HeaderWithSearchBar.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/ScrollToTop.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/sign-in/FailPage.jsx
Labels: ♻️ Refactor, 🚨 Hotfix, 👨‍⚕️QA

#223 ♻️ Refactor : 종료된 커피챗 버튼 문구 변경 및 로딩 문구 자동변경 반영
  src/pages/coffee-detail/CoffeeDetailButtons.jsx
  src/pages/coffeechat/Coffee.jsx
  src/pages/jd-all/JDComponent.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/mypage/FavoritesVideo.jsx
Labels: 🐛 Fix, ♻️ Refactor, 🚨 Hotfix

#238 🐛 Fix : JD 상세화면 로그인 검사 alert 수정 및 회원가입 자동 리다이렉트 수정
  src/pages/info/InFo.jsx
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/jd-detail/useReviewPagination.jsx
Labels: 🐛 Fix, ♻️ Refactor, 👨‍⚕️QA

#247 🐛 Fix : 회원정보수정 api url 수정
  src/api/api.js
  src/components/common/swipe/SwipJobSkill.jsx
  src/pages/mypage/InfoEdit.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#249 ✨ Feat : jd 상세 페이지 "사이트로 이동하기" 버튼 fixed 설정 & 절대경로 설정
  public/111logo192.png
  public/11favicon.ico
  src/App.jsx
  src/assets/images/profile.svg
  src/components/common/GenderBtn.jsx
  src/components/common/InputField.jsx
  src/components/common/card/CompanyCard/index.jsx
  src/components/common/card/VideoCard/index.jsx
  src/components/common/filters/Filters copy.jsx
  src/pages/coffee-detail/CoffeeChatInfo.jsx
  src/pages/coffee-detail/CoffeeDetail.jsx
  src/pages/coffee-detail/HostInfoWithViewcount.jsx
  src/pages/coffee-detail/UpdateCoffeeForm.jsx
  src/pages/info/Done.jsx
  src/pages/info/InfoJD.jsx
  src/pages/info/InfoSkill.jsx
  src/pages/info/InfoStyles.js
  src/pages/info/SignupFail.jsx
  src/pages/jd-detail/JdDetail.jsx
  src/pages/jd-detail/ReviewPopup.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/useAddReview.jsx
  src/pages/jd-detail/useDeleteReview.jsx
  src/pages/jd-detail/useReviewPagination.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/mainpage/SubmitBug.jsx
  src/pages/mainpage/VideoSection.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/mypage/ProfileSection.jsx
  src/pages/mypage/Withdrawal.jsx
  src/pages/sign-in/SignIn.jsx
  src/pages/sign-in/TitleLogo.jsx
Labels: ✨ Feat, 📦 Chore

#256 ♻️ Refactor : Header 공동 컴포넌트 수정
  src/components/common/Header.jsx
  src/constants/headerProps.js
  src/pages/coffee-detail/CoffeeDetail.jsx
  src/pages/coffee-detail/UpdateCoffeeForm.jsx
  src/pages/coffeechat/CoffeeOpen.jsx
  src/pages/jd-detail/JdDetail.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🐛 Fix, ♻️ Refactor, 👨‍⚕️QA

#259 ♻️ Refactor : API 연속호출 이슈 해결 및 alert, confirm 안내 문구 형식 통일 완료
  src/api/api.js
  src/components/common/card/CoffeeChatCard/index.jsx
  src/components/common/card/VideoCard/index.jsx
  src/components/common/constant.jsx
  src/components/common/swipe/SwipJobSkill.jsx
  src/constants/headerProps.js
  src/pages/coffeechats/FiltersAndButton.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeDetailButtons.jsx
  src/pages/info/InFo.jsx
  src/pages/info/InfoSkill.jsx
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/jd-detail/useAddReview.jsx
  src/pages/jd-detail/useDeleteReview.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mainpage/VideoSection.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🐛 Fix, ♻️ Refactor, 👨‍⚕️QA

#265 ♻️ Refactor : 회원 탈퇴 방식 수정
  src/components/common/navigation-btn/NavigationBtnStyles.js
  src/pages/jd-all/JDComponent.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🐛 Fix, 💄 Style, 👨‍⚕️QA

#266 🐛 Fix :무한스크롤 구현/회원가입 폼 수정/filter값 유지
  src/api/api.js
  src/components/common/BottomNav.jsx
  src/components/common/filters/Filters.jsx
  src/components/common/modal/CommonModal.jsx
  src/pages/coffeechats/FiltersAndButton.jsx
  src/pages/coffeechats/components/Filters/FilterChips.jsx
  src/pages/coffeechats/components/Filters/RadioOptionsGroup.jsx
  src/pages/coffeechats/components/Filters/index.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/dateUtils.js
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeDetailButtons.jsx
  src/pages/coffeechats/detail-coffeechats/index.jsx
  src/pages/coffeechats/hooks/useForm.jsx
  src/pages/coffeechats/index.jsx
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/coffeechats/useFilterPersistence.jsx
  src/pages/info/DetailDialog.jsx
  src/pages/info/InFo.jsx
  src/pages/info/InFoBasic.jsx
  src/pages/info/TermsAndConditions.jsx
  src/pages/jd-detail/useReviewPagination.jsx
Labels: ✨ Feat, 🐛 Fix, 💄 Style, 👨‍⚕️QA

#267 🐛 Fix : 커피챗 수정 페이지 뒤로가기 버튼 동작 이슈 해결 및 console.log 정리
  src/api/api.js
  src/components/common/ToggleList.jsx
  src/components/common/card/CoffeeChatCard/CoffeeChatCardStyle.js
  src/components/common/card/VideoCard/index.jsx
  src/components/common/swipe/SwipJobSkill copy.jsx
  src/constants/headerProps.js
  src/pages/coffeechats/detail-coffeechats/CoffeeDetailButtons.jsx
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/coffeechats/useFilterPersistence.jsx
  src/pages/info/InFo.jsx
  src/pages/info/InFoBasic.jsx
  src/pages/info/InfoSkill.jsx
  src/pages/jd-detail/useReviewPagination.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mypage/LogoutButton.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🐛 Fix, 📦 Chore

#277 🐛 Fix : 인프런 강의 수강자 수 toLocaleString 추가
  src/components/common/card/VideoCard/index.jsx
  src/pages/jd-detail/CategoryTab.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#283 📦 Chore : 회원정보 기술스택 alert 메세지 수정
  .github/ISSUE_TEMPLATE/issue_template copy.yml
  src/components/common/swipe/SwipJobSkill.jsx
Labels: 📦 Chore, 👨‍⚕️QA

#291 💄 Design : 로그인 버튼 pointer 속성 추가
  src/pages/PageStyles.js
  src/pages/sign-in/LoginBtn.jsx
Labels: 💄 Style, 👨‍⚕️QA

#292 🐛 Fix : build yml 수정
  .github/workflows/Build_React_App.yml
Labels: 📦 Chore, 🚨 Hotfix

#293 🚨 Hotfix : 서버 환경에서 환경변수를 참조하지 못하는 이슈발견 및 수정
  src/api/api.js
Labels: 🚨 Hotfix

#295 🚨 Fix : 환경변수 변경
  .github/workflows/Build_React_App.yml
  src/api/api.js
  src/pages/sign-in/LoginBtn.jsx
Labels: 🚨 Hotfix

#297 🚨 Hotfix : 재 배포
  .github/workflows/Build_React_App.yml
  src/pages/mainpage/Main.jsx
Labels: 🚨 Hotfix

#299 📦 Chore : meta 및 title 태그 변경
  public/index.html
  src/App.jsx
Labels: 📦 Chore, 👨‍⚕️QA

#304 Fix/#211
  src/api/api.js
  src/components/common/card/CoffeeChatCard/CardBody.jsx
  src/components/common/card/CoffeeChatCard/CoffeeChatCardStyle.js
  src/components/common/card/CoffeeChatCard/index.jsx
  src/components/common/new-btn/RoundButton.jsx
  src/pages/PageStyles.js
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/userInfoItem.jsx
  src/pages/coffeechats/hooks/useForm.jsx
  src/pages/coffeechats/index.jsx
  src/pages/mypage/MyCoffeeChat.jsx
Labels: ✨ Feat, 🐛 Fix, 👨‍⚕️QA

#306 📦 Chore : 배포 yml 파일 변경
  .github/workflows/Build_React_App.yml
Labels: 📦 Chore, 🚨 Hotfix

#308 📦 Chore : 누락사항 변경
  .github/workflows/Build_React_App.yml
Labels: 📦 Chore, 🚨 Hotfix

#309 📦 Chore : 진짜 마지막 yml 수정
  .github/workflows/Build_React_App.yml
Labels: 📦 Chore, 🚨 Hotfix

#310 ✨ Feat : 커피챗 생성 페이지에서 유저 정보 UI 추가
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/styles.js
  src/pages/coffeechats/create-coffeechats/userInfoItem.jsx
Labels: ✨ Feat

#311 📦 Chore : 제발..
  .github/workflows/Build_React_App.yml
Labels: 📦 Chore, 🚨 Hotfix

#312 🐛 Fix : main화면 api 무한호출 에러 수정 및 로그인 후 이전페이지로 이동기능 추가
  src/components/common/card/VideoCard/index.jsx
  src/components/common/constant.jsx
  src/pages/coffeechats/FiltersAndButton.jsx
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mainpage/useLoadData.jsx
  src/pages/sign-in/RedirectPage.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#313 🐛 Fix : 리뷰 api 호출 부분 수정 & 커피챗 수정 에러 메세지 alert 띄우기
  src/components/common/new-btn/RoundButton.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/styles.js
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/jd-detail/ReviewItem.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/useReviewPagination.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#314 🐛 Fix : 키워드 반영되지 않는 이슈 해결
  src/pages/mainpage/useLoadData.jsx
Labels: 🐛 Fix, 🚨 Hotfix

#315 🚀Deploy : 운영서버 배포
  README.md
  src/components/common/new-btn/RoundButton.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/styles.js
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/jd-detail/ReviewItem.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/useReviewPagination.jsx
  src/pages/mainpage/useLoadData.jsx
Labels: 🚀Deploy

#317 🐛 Fix : 커피챗 삭제 -> 취소로 변경
  src/api/api.js
  src/components/common/card/CoffeeChatCard/CardBody.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/pages/mypage/MyCoffeeChat.jsx
Labels: 🐛 Fix

#319 🚀Deploy : 운영서버 배포
  src/App.jsx
  src/api/api.js
  src/components/common/card/CoffeeChatCard/CardBody.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/pages/info/SignupFail.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/sign-in/FailPage.jsx
  src/pages/sign-in/hooks/useSetErrorMsg.jsx
Labels: 🚀Deploy

#320 🚨 Hotfix : JD 목록페이지에 들어가지 못하던 문제 해결
  src/components/common/BottomNav.jsx
  src/constants/headerProps.js
  src/pages/jd-all/index.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🚨 Hotfix

#321 🚀Deploy : 운영서버 오류 핫픽스
  src/components/common/BottomNav.jsx
  src/constants/headerProps.js
  src/pages/jd-all/index.jsx
  src/pages/mypage/Withdrawal.jsx
Labels: 🚨 Hotfix, 🚀Deploy

#322 🐛 Fix : 필터 유지 기능 수정
  src/App.jsx
  src/pages/coffeechats/FiltersAndButton.jsx
  src/pages/coffeechats/components/Filters/RadioOptionsGroup.jsx
  src/pages/coffeechats/components/Filters/index.jsx
  src/pages/coffeechats/components/badge/JobBadge.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/coffeechats/detail-coffeechats/HostInfoWithViewcount.jsx
  src/pages/coffeechats/detail-coffeechats/index.jsx
  src/pages/coffeechats/index.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mainpage/hooks/useAuth.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#323 ✨ Feat : 프리티어 설정 및 커피챗 페이지 page 번호 유지
  .eslintrc.js
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/components/assets/button/MyButton.jsx
  src/components/common/Pagenation.jsx
  src/components/common/card/CoffeeChatCard/BadgeForStatus.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/components/common/new-btn/RoundButton.jsx
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/pages/coffeechats/components/Filters/RadioOptionsGroup.jsx
  src/pages/coffeechats/components/Filters/index.jsx
  src/pages/coffeechats/components/badge/JobBadge.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/styles.js
  src/pages/coffeechats/create-coffeechats/userInfoItem.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeDetailButtons.jsx
  src/pages/coffeechats/detail-coffeechats/HostInfoWithViewcount.jsx
  src/pages/coffeechats/index.jsx
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/info/SignupFail.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/useReviewPagination.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/sign-in/FailPage.jsx
  src/pages/sign-in/hooks/useSetErrorMsg.jsx
  src/pages/sign-in/index.scss
Labels: 🐛 Fix, 👨‍⚕️QA

#324 🐛 Fix : 내가 작성한 커피챗이 아니면 수정폼 접근 금지
  src/components/common/Loading.jsx
  src/pages/coffeechats/detail-coffeechats/index.jsx
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/coffeechats/useFilterPersistence.jsx
Labels: 👨‍⚕️QA

#326 🐛 Fix : 키워드 값 localStorage 저장
  src/components/common/BottomNav.jsx
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/search-bar/index.jsx
  src/pages/coffeechats/coffeechat-list/index.jsx
  src/pages/coffeechats/hooks/useFetchCoffeeData.jsx
Labels: 🐛 Fix

#328 🐛 Fix : 마이페이지 커피챗 상태저장 & 이전페이지 이동 수정 및 메인페이지 검색오류 수정
  .eslintrc.js
  src/components/common/Header.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/constants/headerProps.js
  src/pages/coffeechats/detail-coffeechats/index.jsx
  src/pages/mainpage/useLoadData.jsx
  src/pages/mypage/MyCoffeeChat.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#330 🐛 Fix : 마이페이지 페이지네이션 api 연동 & divider padding 추가
  package-lock.json
  package.json
  src/api/api.js
  src/components/common/card/VideoCard/index.jsx
  src/pages/coffeechats/coffeechat-list/index.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/info/InFo.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/InfoEdit.jsx
Labels: 🐛 Fix, 👨‍⚕️QA

#329 🚀Deploy
  .eslintrc.js
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/api/api.js
  src/components/assets/button/MyButton.jsx
  src/components/common/BottomNav.jsx
  src/components/common/Header.jsx
  src/components/common/Loading.jsx
  src/components/common/Pagenation.jsx
  src/components/common/card/CoffeeChatCard/BadgeForStatus.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/components/common/card/VideoCard/index.jsx
  src/components/common/new-btn/RoundButton.jsx
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/search-bar/SearchBar.jsx
  src/components/common/search-bar/SearchBarStyles.js
  src/components/common/search-bar/SelectOption.jsx
  src/components/common/search-bar/index.jsx
  src/constants/headerProps.js
  src/pages/coffeechats/coffeechat-list/CoffeeBanner.jsx
  src/pages/coffeechats/coffeechat-list/FiltersAndButton.jsx
  src/pages/coffeechats/coffeechat-list/index.jsx
  src/pages/coffeechats/components/Filters/RadioOptionsGroup.jsx
  src/pages/coffeechats/components/Filters/index.jsx
  src/pages/coffeechats/components/badge/JobBadge.jsx
  src/pages/coffeechats/create-coffeechats/index.jsx
  src/pages/coffeechats/create-coffeechats/styles.js
  src/pages/coffeechats/create-coffeechats/userInfoItem.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeDetailButtons.jsx
  src/pages/coffeechats/detail-coffeechats/HostInfoWithViewcount.jsx
  src/pages/coffeechats/detail-coffeechats/index.jsx
  src/pages/coffeechats/hooks/useFetchCoffeeData.jsx
  src/pages/coffeechats/hooks/useFetchJobCategory.jsx
  src/pages/coffeechats/index.jsx
  src/pages/coffeechats/style.js
  src/pages/coffeechats/update-coffeechats/index.jsx
  src/pages/coffeechats/useFilterPersistence.jsx
  src/pages/info/InFo.jsx
  src/pages/info/SignupFail.jsx
  src/pages/jd-detail/TabForReview.jsx
  src/pages/jd-detail/useReviewPagination.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/StickyTabSection.jsx
  src/pages/mainpage/hooks/useAuth.jsx
  src/pages/mainpage/useLoadData.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/InfoEdit.jsx
  src/pages/mypage/MyCoffeeChat.jsx
  src/pages/sign-in/FailPage.jsx
  src/pages/sign-in/hooks/useSetErrorMsg.jsx
  src/pages/sign-in/index.scss
  src/recoil/atoms.jsx
Labels: 🚀Deploy

#332 ✨ Feat : video & company skeleton ui
  src/App.jsx
  src/components/DeferredComponent.jsx
  src/components/assets/button/MyButton.jsx
  src/components/common/card/CompanyCard/index.jsx
  src/components/common/card/VideoCard/index.jsx
  src/components/common/skeleton/company-card/CompanyCardSkeleton.jsx
  src/components/common/skeleton/company-card/SkeletonLoader.jsx
  src/components/common/skeleton/video-card/SkeletonLoader.jsx
  src/components/common/skeleton/video-card/VideoCardSkeleton.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/SubmitBug.jsx
  src/pages/mainpage/VideoSection.jsx
  src/pages/mainpage/components/DataNone.jsx
  src/pages/mainpage/components/ScrollToTop.jsx
  src/pages/mainpage/components/SubmitBug.jsx
  src/pages/mainpage/components/company-section/CompanyList.jsx
  src/pages/mainpage/components/company-section/CompanyTitle.jsx
  src/pages/mainpage/components/company-section/SkeletonCompanySection.jsx
  src/pages/mainpage/components/company-section/index.jsx
  src/pages/mainpage/components/tab/StickyTabSection.jsx
  src/pages/mainpage/components/video-section/SkeletonVideoSection.jsx
  src/pages/mainpage/components/video-section/VideoList.jsx
  src/pages/mainpage/components/video-section/VideoTitle.jsx
  src/pages/mainpage/components/video-section/index.jsx
  src/pages/mainpage/cookie.js
  src/pages/mainpage/hooks/useLoadData.jsx
  src/pages/mainpage/index.jsx
  src/pages/mainpage/style.js
Labels: ✨ Feat

#333 🚑️ Hotfix: 검색어 유지 버그 해결
  src/components/common/search-bar/HeaderWithSearchBar.jsx
Labels: 🚨 Hotfix

#334 🚀Deploy
  src/App.jsx
  src/api/api.js
  src/components/DeferredComponent.jsx
  src/components/assets/button/MyButton.jsx
  src/components/common/card/CompanyCard/index.jsx
  src/components/common/card/VideoCard/index.jsx
  src/components/common/modal/CommonModal.jsx
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/search-bar/SelectOption.jsx
  src/components/common/search-bar/index.jsx
  src/components/common/skeleton/company-card/CompanyCardSkeleton.jsx
  src/components/common/skeleton/company-card/SkeletonLoader.jsx
  src/components/common/skeleton/video-card/SkeletonLoader.jsx
  src/components/common/skeleton/video-card/VideoCardSkeleton.jsx
  src/components/common/swipe/SwipJobSkill.jsx
  src/constants/jdAllFilter/index.js
  src/constants/swipJobSkill/index.js
  src/pages/coffeechats/coffeechat-list/index.jsx
  src/pages/coffeechats/detail-coffeechats/CoffeeChatInfo.jsx
  src/pages/jd-all/JDComponent.jsx
  src/pages/jd-all/JDSearchBar.jsx
  src/pages/jd-all/components/JDComponent/index.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/Filters/FilterChips.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/Filters/RadioOptionsGroup.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/Filters/index.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/index.jsx
  src/pages/jd-all/components/JDSearchBar/index.jsx
  src/pages/jd-all/hooks/useFetchJobCategory.jsx
  src/pages/jd-all/hooks/useJDComponents.jsx
  src/pages/jd-all/hooks/useJDSearchBar.jsx
  src/pages/jd-all/index.jsx
  src/pages/mainpage/CompanySection.jsx
  src/pages/mainpage/Main.jsx
  src/pages/mainpage/SubmitBug.jsx
  src/pages/mainpage/VideoSection.jsx
  src/pages/mainpage/components/DataNone.jsx
  src/pages/mainpage/components/ScrollToTop.jsx
  src/pages/mainpage/components/SubmitBug.jsx
  src/pages/mainpage/components/company-section/CompanyList.jsx
  src/pages/mainpage/components/company-section/CompanyTitle.jsx
  src/pages/mainpage/components/company-section/SkeletonCompanySection.jsx
  src/pages/mainpage/components/company-section/index.jsx
  src/pages/mainpage/components/tab/StickyTabSection.jsx
  src/pages/mainpage/components/video-section/SkeletonVideoSection.jsx
  src/pages/mainpage/components/video-section/VideoList.jsx
  src/pages/mainpage/components/video-section/VideoTitle.jsx
  src/pages/mainpage/components/video-section/index.jsx
  src/pages/mainpage/cookie.js
  src/pages/mainpage/hooks/useLoadData.jsx
  src/pages/mainpage/index.jsx
  src/pages/mainpage/style.js
  src/pages/mypage/MyPage.jsx
Labels: 🚀Deploy

#336 ✨ Feat : JD목록 및 찜 페이지 스켈레톤 UI 추가 & 헤더 JDON 리다이렉트 기능 추가
  src/api/api.js
  src/assets/font/Pretendard-Regular.otf
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/skeleton/company-card/CompanyCardSkeleton.jsx
  src/components/common/skeleton/video-card/VideoCardSkeleton.jsx
  src/index.css
  src/pages/coffeechats/components/badge/JobBadge.jsx
  src/pages/jd-all/components/JDComponent/JDGird.jsx
  src/pages/jd-all/components/JDComponent/index.jsx
  src/pages/jd-all/hooks/useJDComponents.jsx
  src/pages/mainpage/hooks/useLoadData.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/Withdrawal.jsx
  src/styles/themeMuiStyle.js
Labels: ✨ Feat, 🐛 Fix

#337 🚀Deploy
  src/api/api.js
  src/assets/font/Pretendard-Regular.otf
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/skeleton/company-card/CompanyCardSkeleton.jsx
  src/components/common/skeleton/video-card/VideoCardSkeleton.jsx
  src/index.css
  src/pages/coffeechats/components/badge/JobBadge.jsx
  src/pages/jd-all/components/JDComponent/JDGird.jsx
  src/pages/jd-all/components/JDComponent/index.jsx
  src/pages/jd-all/hooks/useJDComponents.jsx
  src/pages/mainpage/hooks/useLoadData.jsx
  src/pages/mypage/FavoritesVideo.jsx
  src/pages/mypage/Withdrawal.jsx
  src/styles/themeMuiStyle.js
Labels: 🚀Deploy

#339 ✨ Feat : 검색어 길이제한 유효성 검사 추가 및 clear버튼 추가
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/search-bar/SearchBarStyles.js
  src/components/common/search-bar/index.jsx
  src/pages/coffeechats/coffeechat-list/FiltersAndButton.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/index.jsx
  src/pages/mainpage/components/company-section/CompanyTitle.jsx
  src/pages/mainpage/components/tab/StickyTabSection.jsx
  src/pages/mainpage/components/video-section/index.jsx
Labels: ✨ Feat, 🐛 Fix

#340 💄 Design : JD 상세페이지 이미지 스타일 수정
  src/assets/images/ProfileIcon.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/jd-detail/style.js
  src/pages/mainpage/components/company-section/CompanyTitle.jsx
  src/pages/mainpage/components/video-section/index.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/ProfileSection.jsx
Labels: ♻️ Refactor, 💄 Style

#341 🚀Deploy
  src/assets/images/ProfileIcon.jsx
  src/components/common/search-bar/HeaderWithSearchBar.jsx
  src/components/common/search-bar/SearchBarStyles.js
  src/components/common/search-bar/index.jsx
  src/pages/coffeechats/coffeechat-list/FiltersAndButton.jsx
  src/pages/jd-all/components/JDSearchBar/FiltersAndButton/index.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/jd-detail/style.js
  src/pages/mainpage/components/company-section/CompanyTitle.jsx
  src/pages/mainpage/components/tab/StickyTabSection.jsx
  src/pages/mainpage/components/video-section/index.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/ProfileSection.jsx
Labels: 🚀Deploy

#345 ♻️ Refactor : 커피챗 신청&수정 폼
  package-lock.json
  package.json
  src/App.jsx
  src/components/coffeechats/List/queryHooks/useFetchCoffeeData.jsx
  src/components/coffeechats/List/queryHooks/useSearch.jsx
  src/components/coffeechats/List/queryHooks/useSort.jsx
  src/components/coffeechats/List/style.js
  src/components/coffeechats/List/ui/InfoItemWrapper.jsx
  src/components/coffeechats/List/ui/UserInfo.jsx
  src/components/coffeechats/Update/queryHooks/useFetchCoffeeChatDetail.jsx
  src/components/coffeechats/Update/queryHooks/useRegisterCoffeeChat.jsx
  src/components/coffeechats/Update/ui/UpdateCoffeeChatForm.jsx
  src/components/coffeechats/create/queryHooks/useSubmitCoffeeChat.jsx
  src/components/coffeechats/create/ui/CreateCoffeeChatForm.jsx
  src/components/coffeechats/detail/queryHooks/useFetchcCoffeeChatDetail.jsx
  src/components/coffeechats/detail/ui/CoffeeDetailButtons.jsx
  src/components/coffeechats/detail/ui/CoffeeListComponent.jsx
  src/components/coffeechats/detail/ui/DynamicHeader.jsx
  src/components/coffeechats/detail/ui/button/ApplyButton.jsx
  src/components/coffeechats/detail/ui/index.jsx
  src/components/common/button/ActionButton.jsx
  src/components/common/button/DuplicateCheckButton.jsx
  src/components/common/button/NavigationBtnStyles.js
  src/components/common/button/NewBtn.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/components/common/form/CoffeeChatForm.jsx
  src/components/member/sign-up/ui/StepForBasic.jsx
  src/hooks/useCoffeeForm.jsx
  src/hooks/useFetchJobCategory.jsx
  src/hooks/useValidateForm.jsx
  src/pages/CoffeeDetailPage.jsx
  src/pages/CoffeeListPage.jsx
  src/pages/jd-detail/CategoryTab.jsx
Labels: ♻️ Refactor

#347 🚑️ Hotfix: 경로 수정 및 폴더명 변경
  src/components/coffeechats/create-coffeechats/queryHooks/useSubmitCoffeeChat.jsx
  src/components/coffeechats/create-coffeechats/styles.js
  src/components/coffeechats/create-coffeechats/ui/CreateCoffeeChatForm.jsx
  src/components/coffeechats/create-coffeechats/ui/userInfoItem.jsx
  src/components/coffeechats/detail-coffeechats/queryHooks/useClipboardCopy.jsx
  src/components/coffeechats/detail-coffeechats/queryHooks/useFetchcCoffeeChatDetail.jsx
  src/components/coffeechats/detail-coffeechats/styles.js
  src/components/coffeechats/detail-coffeechats/ui/CoffeeChatLink.jsx
  src/components/coffeechats/detail-coffeechats/ui/CoffeeContent.jsx
  src/components/coffeechats/detail-coffeechats/ui/CoffeeDetailButtons.jsx
  src/components/coffeechats/detail-coffeechats/ui/CoffeeInfoItem.jsx
  src/components/coffeechats/detail-coffeechats/ui/CoffeeTitle.jsx
  src/components/coffeechats/detail-coffeechats/ui/DynamicHeader.jsx
  src/components/coffeechats/detail-coffeechats/ui/HostInfoWithViewcount.jsx
  src/components/coffeechats/detail-coffeechats/ui/RecruitmentInfo.jsx
  src/components/coffeechats/detail-coffeechats/ui/URLShareButton.jsx
  src/components/coffeechats/detail-coffeechats/ui/button/ApplyButton.jsx
  src/components/coffeechats/detail-coffeechats/ui/button/EditButton.jsx
  src/components/coffeechats/detail-coffeechats/ui/button/RemoveButton.jsx
  src/components/coffeechats/detail-coffeechats/ui/index.jsx
  src/components/coffeechats/edit-coffeechats/queryHooks/useFetchCoffeeChatDetail.jsx
  src/components/coffeechats/edit-coffeechats/queryHooks/useRegisterCoffeeChat.jsx
  src/components/coffeechats/edit-coffeechats/ui/UpdateCoffeeChatForm.jsx
  src/components/coffeechats/list-coffeechats/queryHooks/useFetchCoffeeData.jsx
  src/components/coffeechats/list-coffeechats/queryHooks/useLoginCheckAndRedirect.jsx
  src/components/coffeechats/list-coffeechats/queryHooks/useSearch.jsx
  src/components/coffeechats/list-coffeechats/queryHooks/useSort.jsx
  src/components/coffeechats/list-coffeechats/style.js
  src/components/coffeechats/list-coffeechats/ui/CoffeeListComponent.jsx
  src/components/coffeechats/list-coffeechats/ui/CoffeePagenation.jsx
  src/components/coffeechats/list-coffeechats/ui/CreateCoffeeChatButton.jsx
  src/components/coffeechats/list-coffeechats/ui/FiltersAndButton.jsx
  src/components/coffeechats/list-coffeechats/ui/InfoItemWrapper.jsx
  src/components/coffeechats/list-coffeechats/ui/UserInfo.jsx
  src/pages/CoffeeCreatePage.jsx
  src/pages/CoffeeDetailPage.jsx
  src/pages/CoffeeListPage.jsx
  src/pages/CoffeeUpdatePage.jsx
Labels: 🚨 Hotfix

#349 ✨ Feat : 커피챗 상세페이지 상태뱃지 추가 & 신청하기 버튼 클릭 시 자동 업데이트
  src/components/coffeechats/detail-coffeechats/queryHooks/useApplyForCoffeeChat.jsx
  src/components/coffeechats/detail-coffeechats/ui/HostInfoWithViewcount.jsx
  src/components/coffeechats/detail-coffeechats/ui/button/ApplyButton.jsx
  src/components/common/badge/BadgeForJob.jsx
  src/components/common/badge/BadgeForStatus.jsx
  src/components/common/card/CoffeeChatCard/BadgeForJob.jsx
  src/components/common/card/CoffeeChatCard/BadgeForStatus.jsx
  src/components/common/card/CoffeeChatCard/CardBody.jsx
  src/components/common/card/CoffeeChatCard/CardHeader.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
  src/hooks/useFetchJobCategory.jsx
Labels: ✨ Feat

#350 💄 Style : JDS 상세페이지 채용기한 관련 UI 추가 및 스켈레톤 UI 추가
  package-lock.json
  public/index.html
  src/assets/icons/favicon.ico
  src/components/DeferredComponent.jsx
  src/components/common/alert/index.jsx
  src/components/common/loading/skeleton/jd-detail/content.jsx
  src/components/common/loading/skeleton/jd-detail/img.jsx
  src/components/common/loading/skeleton/jd-detail/title.jsx
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/mainpage/components/video-section/SkeletonVideoSection.jsx
  src/pages/mypage/InfoEdit.jsx
  src/recoil/atoms.jsx
Labels: ✨ Feat, 💄 Style

#352 🚨 Hotfix : 파비콘 및 마감 일자 미표기 이슈 해결
  public/index.html
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/mypage/LogoutButton.jsx
Labels: 🐛 Fix, 🚨 Hotfix

#353 🚀Deploy
  public/index.html
  src/pages/jd-detail/TabForInfo.jsx
  src/pages/mypage/LogoutButton.jsx
Labels: 🚀Deploy

#356 🚀Deploy
  src/App.jsx
  src/components/common/card/CoffeeChatCard/index.jsx
Labels: 🚀Deploy

#360 🐛 Fix : 커피챗 신청하기 400 에러 핸들링
  src/components/coffeechats/detail-coffeechats/queryHooks/useApplyForCoffeeChat.jsx
Labels: 🐛 Fix

#361 🚀Deploy
  src/App.jsx
  src/api/api.js
  src/components/coffeechats/detail-coffeechats/queryHooks/useApplyForCoffeeChat.jsx
  src/components/coffeechats/list-coffeechats/ui/CoffeeListComponent.jsx
  src/components/common/date-picker/NewDayPicker.jsx
  src/components/common/loading/skeleton/coffeechat-card/CoffeeChatCardSkeleton.jsx
  src/components/common/loading/skeleton/coffeechat-card/SkeletonLoader.jsx
  src/pages/mypage/LogoutButton.jsx
  src/pages/mypage/Withdrawal.jsx
  src/pages/sign-in/RedirectPage.jsx
Labels: 🚀Deploy

#362 🚑️ Hotfix: search api 무한호출 수정 & 커피챗 skeleton ui 지연시간 발생
  src/components/coffeechats/list-coffeechats/queryHooks/useFetchCoffeeData.jsx
  src/constants/delay.js
  src/pages/mainpage/apiFunction.js
Labels: 🚨 Hotfix

#363 🚀Deploy
  src/components/coffeechats/list-coffeechats/queryHooks/useFetchCoffeeData.jsx
  src/constants/delay.js
  src/pages/mainpage/apiFunction.js
Labels: 🚀Deploy

#364 ♻️ Refactor : 다이나믹 헤더 수정 및 폴더 경로 이동
  src/App.jsx
  src/components/coffeechats/detail-coffeechats/ui/DynamicHeader.jsx
  src/pages/coffeechats/CoffeeCreatePage.jsx
  src/pages/coffeechats/CoffeeDetailPage.jsx
  src/pages/coffeechats/CoffeeListPage.jsx
  src/pages/coffeechats/CoffeeUpdatePage.jsx
  src/pages/sign-up/SignUpFailPage.jsx
  src/pages/sign-up/SignUpPage.jsx
  src/pages/sign-up/SignUpSuccessPage.jsx
Labels: ♻️ Refactor

#365 🚨 Hotfix : JD 상세페이지 로그인 관련 이슈
  src/pages/jd-detail/JdDetail.jsx
Labels: 🚨 Hotfix

#368 🚨 Fix : 로그인 후 메인페이지로 이동 fix
  src/pages/sign-in/RedirectPage.jsx
Labels: 🚨 Hotfix

#369 🚀Deploy
  src/App.jsx
  src/components/coffeechats/detail-coffeechats/ui/DynamicHeader.jsx
  src/pages/coffeechats/CoffeeCreatePage.jsx
  src/pages/coffeechats/CoffeeDetailPage.jsx
  src/pages/coffeechats/CoffeeListPage.jsx
  src/pages/coffeechats/CoffeeUpdatePage.jsx
  src/pages/jd-detail/CategoryTab.jsx
  src/pages/sign-in/RedirectPage.jsx
  src/pages/sign-up/SignUpFailPage.jsx
  src/pages/sign-up/SignUpPage.jsx
  src/pages/sign-up/SignUpSuccessPage.jsx
Labels: 🚀Deploy
